/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.engine.jdbc.spi.SqlExceptionHelper;
import org.hibernate.exception.ConstraintViolationException;

/**
 *
 * @author Angel
 */
public class FamiliasDialog extends javax.swing.JDialog {

    public FamiliasDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreFamilia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btAniadirFamilia = new javax.swing.JButton();
        btEliminarFamilia = new javax.swing.JButton();
        btEditarFamilia = new javax.swing.JButton();
        btBuscarFamilia = new javax.swing.JButton();
        btListarArticulos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Familias = new javax.swing.JTable();
        txtCodigoFamilia = new javax.swing.JTextField();
        btRetroceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Codigo de familia");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(0, 10, 0, 0));

        btAniadirFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/plus.png"))); // NOI18N
        btAniadirFamilia.setToolTipText("Añadir familia");
        btAniadirFamilia.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btAniadirFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAniadirFamiliaActionPerformed(evt);
            }
        });
        jToolBar1.add(btAniadirFamilia);

        btEliminarFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/remove.png"))); // NOI18N
        btEliminarFamilia.setToolTipText("Eliminar familia");
        btEliminarFamilia.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btEliminarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarFamiliaActionPerformed(evt);
            }
        });
        jToolBar1.add(btEliminarFamilia);

        btEditarFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar.png"))); // NOI18N
        btEditarFamilia.setToolTipText("Editar familia");
        btEditarFamilia.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btEditarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFamiliaActionPerformed(evt);
            }
        });
        jToolBar1.add(btEditarFamilia);

        btBuscarFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa.png"))); // NOI18N
        btBuscarFamilia.setToolTipText("Buscar familia");
        btBuscarFamilia.setFocusable(false);
        btBuscarFamilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscarFamilia.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btBuscarFamilia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBuscarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarFamiliaActionPerformed(evt);
            }
        });
        jToolBar1.add(btBuscarFamilia);

        btListarArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/list.png"))); // NOI18N
        btListarArticulos.setToolTipText("Listar los articulos de la familia");
        btListarArticulos.setFocusable(false);
        btListarArticulos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btListarArticulos.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btListarArticulos.setName(""); // NOI18N
        btListarArticulos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btListarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarArticulosActionPerformed(evt);
            }
        });
        jToolBar1.add(btListarArticulos);

        jLabel2.setText("Nombre de la familia");

        JT_Familias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo familia", "Nombre familia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_Familias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JT_Familias);
        if (JT_Familias.getColumnModel().getColumnCount() > 0) {
            JT_Familias.getColumnModel().getColumn(0).setResizable(false);
            JT_Familias.getColumnModel().getColumn(1).setResizable(false);
        }

        btRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Retroceder.png"))); // NOI18N
        btRetroceder.setToolTipText("Retroceder ");
        btRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAniadirFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAniadirFamiliaActionPerformed
        
    }//GEN-LAST:event_btAniadirFamiliaActionPerformed

    private void btEliminarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarFamiliaActionPerformed
       
    }//GEN-LAST:event_btEliminarFamiliaActionPerformed

    private void btEditarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFamiliaActionPerformed
        
    }//GEN-LAST:event_btEditarFamiliaActionPerformed

    private void btBuscarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarFamiliaActionPerformed
       
    }//GEN-LAST:event_btBuscarFamiliaActionPerformed

    private void btListarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarArticulosActionPerformed
        
    }//GEN-LAST:event_btListarArticulosActionPerformed

    private void btRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetrocederActionPerformed
        

    }//GEN-LAST:event_btRetrocederActionPerformed

    //----------------------Metodos auxiliares----------------------------------
    private void actualizarTablaFamilias() {
        

    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamiliasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamiliasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamiliasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamiliasDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FamiliasDialog dialog = new FamiliasDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_Familias;
    private javax.swing.JButton btAniadirFamilia;
    private javax.swing.JButton btBuscarFamilia;
    private javax.swing.JButton btEditarFamilia;
    private javax.swing.JButton btEliminarFamilia;
    private javax.swing.JButton btListarArticulos;
    private javax.swing.JButton btRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtCodigoFamilia;
    private javax.swing.JTextField txtNombreFamilia;
    // End of variables declaration//GEN-END:variables
}
