package modelos;
// Generated 01-dic-2023 20:26:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private String codart;
     private Familias familias;
     private String nomart;
     private BigDecimal precio;
     private Set facturases = new HashSet(0);

    public Articulos() {
    }

	
    public Articulos(String codart) {
        this.codart = codart;
    }
    public Articulos(String codart, Familias familias, String nomart, BigDecimal precio, Set facturases) {
       this.codart = codart;
       this.familias = familias;
       this.nomart = nomart;
       this.precio = precio;
       this.facturases = facturases;
    }
   
    public String getCodart() {
        return this.codart;
    }
    
    public void setCodart(String codart) {
        this.codart = codart;
    }
    public Familias getFamilias() {
        return this.familias;
    }
    
    public void setFamilias(Familias familias) {
        this.familias = familias;
    }
    public String getNomart() {
        return this.nomart;
    }
    
    public void setNomart(String nomart) {
        this.nomart = nomart;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


