package modelos;
// Generated 01-dic-2023 20:26:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String codcli;
     private String nombrecliente;
     private Set facturases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String codcli) {
        this.codcli = codcli;
    }
    public Clientes(String codcli, String nombrecliente, Set facturases) {
       this.codcli = codcli;
       this.nombrecliente = nombrecliente;
       this.facturases = facturases;
    }
   
    public String getCodcli() {
        return this.codcli;
    }
    
    public void setCodcli(String codcli) {
        this.codcli = codcli;
    }
    public String getNombrecliente() {
        return this.nombrecliente;
    }
    
    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


